//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class CMSTemplates_CorporateSite_HomeASPX {
    
    /// <summary>
    /// TopText control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.DocumentEngine.Web.UI.CMSEditableRegion TopText;
    
    /// <summary>
    /// MobileDeviceRedirection control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_General_MobileDeviceRedirection MobileDeviceRedirection;
    
    /// <summary>
    /// ContentText control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.DocumentEngine.Web.UI.CMSEditableRegion ContentText;
    
    /// <summary>
    /// wpcNewsletterSubscription control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.PortalEngine.Web.UI.WebPartContainer wpcNewsletterSubscription;
    
    /// <summary>
    /// NewsletterSubscription control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Newsletters_NewsletterSubscriptionWebPart NewsletterSubscription;
    
    /// <summary>
    /// wpcFeaturedProducts control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.PortalEngine.Web.UI.WebPartContainer wpcFeaturedProducts;
    
    /// <summary>
    /// FeaturedProduct control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Ecommerce_Products_RandomProducts FeaturedProduct;
    
    /// <summary>
    /// wpcNews control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.PortalEngine.Web.UI.WebPartContainer wpcNews;
    
    /// <summary>
    /// News control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Viewers_Effects_ScrollingText News;
    
    /// <summary>
    /// wpcPoll control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.PortalEngine.Web.UI.WebPartContainer wpcPoll;
    
    /// <summary>
    /// Poll control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Polls_Poll Poll;
}
