//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.MedioClinic;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ContactSection.CLASS_NAME, typeof(ContactSection))]

namespace CMS.DocumentEngine.Types.MedioClinic
{
	/// <summary>
	/// Represents a content item of type ContactSection.
	/// </summary>
	public partial class ContactSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "MedioClinic.ContactSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContactSection fields.
		/// </summary>
		private readonly ContactSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ContactSectionID.
		/// </summary>
		[DatabaseIDField]
		public int ContactSectionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ContactSectionID"), 0);
			}
			set
			{
				SetValue("ContactSectionID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Subtitle.
		/// </summary>
		[DatabaseField]
		public string Subtitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Subtitle"), @"");
			}
			set
			{
				SetValue("Subtitle", value);
			}
		}


		/// <summary>
		/// Text.
		/// </summary>
		[DatabaseField]
		public string Text
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Text"), @"");
			}
			set
			{
				SetValue("Text", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ContactSection fields.
		/// </summary>
		[RegisterProperty]
		public ContactSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ContactSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContactSectionFields : AbstractHierarchicalObject<ContactSectionFields>
		{
			/// <summary>
			/// The content item of type ContactSection that is a target of the extended API.
			/// </summary>
			private readonly ContactSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContactSectionFields" /> class with the specified content item of type ContactSection.
			/// </summary>
			/// <param name="instance">The content item of type ContactSection that is a target of the extended API.</param>
			public ContactSectionFields(ContactSection instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ContactSectionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ContactSectionID;
				}
				set
				{
					mInstance.ContactSectionID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Subtitle.
			/// </summary>
			public string Subtitle
			{
				get
				{
					return mInstance.Subtitle;
				}
				set
				{
					mInstance.Subtitle = value;
				}
			}


			/// <summary>
			/// Text.
			/// </summary>
			public string Text
			{
				get
				{
					return mInstance.Text;
				}
				set
				{
					mInstance.Text = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContactSection" /> class.
		/// </summary>
		public ContactSection() : base(CLASS_NAME)
		{
			mFields = new ContactSectionFields(this);
		}

		#endregion
	}
}