//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.MedioClinic;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(SocialLinksFolder.CLASS_NAME, typeof(SocialLinksFolder))]

namespace CMS.DocumentEngine.Types.MedioClinic
{
	/// <summary>
	/// Represents a content item of type SocialLinksFolder.
	/// </summary>
	public partial class SocialLinksFolder : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "MedioClinic.SocialLinksFolder";


		/// <summary>
		/// The instance of the class that provides extended API for working with SocialLinksFolder fields.
		/// </summary>
		private readonly SocialLinksFolderFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// SocialLinksFolderID.
		/// </summary>
		[DatabaseIDField]
		public int SocialLinksFolderID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SocialLinksFolderID"), 0);
			}
			set
			{
				SetValue("SocialLinksFolderID", value);
			}
		}


		/// <summary>
		/// Folder name.
		/// </summary>
		[DatabaseField]
		public string FolderName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FolderName"), @"");
			}
			set
			{
				SetValue("FolderName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with SocialLinksFolder fields.
		/// </summary>
		[RegisterProperty]
		public SocialLinksFolderFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with SocialLinksFolder fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class SocialLinksFolderFields : AbstractHierarchicalObject<SocialLinksFolderFields>
		{
			/// <summary>
			/// The content item of type SocialLinksFolder that is a target of the extended API.
			/// </summary>
			private readonly SocialLinksFolder mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="SocialLinksFolderFields" /> class with the specified content item of type SocialLinksFolder.
			/// </summary>
			/// <param name="instance">The content item of type SocialLinksFolder that is a target of the extended API.</param>
			public SocialLinksFolderFields(SocialLinksFolder instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// SocialLinksFolderID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.SocialLinksFolderID;
				}
				set
				{
					mInstance.SocialLinksFolderID = value;
				}
			}


			/// <summary>
			/// Folder name.
			/// </summary>
			public string FolderName
			{
				get
				{
					return mInstance.FolderName;
				}
				set
				{
					mInstance.FolderName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="SocialLinksFolder" /> class.
		/// </summary>
		public SocialLinksFolder() : base(CLASS_NAME)
		{
			mFields = new SocialLinksFolderFields(this);
		}

		#endregion
	}
}