//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class CMSModules_OnlineMarketing_Pages_Widgets_WidgetProperties_Variant {
    
    /// <summary>
    /// cpEditElem control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSModules_OnlineMarketing_Controls_UI_ContentPersonalizationVariant_Edit cpEditElem;
    
    /// <summary>
    /// mvtEditElem control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSModules_OnlineMarketing_Controls_UI_MVTVariant_Edit mvtEditElem;
    
    /// <summary>
    /// hidRefresh control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hidRefresh;
}
