//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.Training;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Article.CLASS_NAME, typeof(Article))]

namespace CMS.DocumentEngine.Types.Training
{
	/// <summary>
	/// Represents a content item of type Article.
	/// </summary>
	public partial class Article : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Training.Article";


		/// <summary>
		/// The instance of the class that provides extended API for working with Article fields.
		/// </summary>
		private readonly ArticleFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ArticleID.
		/// </summary>
		[DatabaseIDField]
		public int ArticleID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ArticleID"), 0);
			}
			set
			{
				SetValue("ArticleID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Teaser image.
		/// </summary>
		[DatabaseField]
		public Guid Image
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("Image"), Guid.Empty);
			}
			set
			{
				SetValue("Image", value);
			}
		}


		/// <summary>
		/// Summary.
		/// </summary>
		[DatabaseField]
		public string Summary
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Summary"), @"");
			}
			set
			{
				SetValue("Summary", value);
			}
		}


		/// <summary>
		/// Text.
		/// </summary>
		[DatabaseField]
		public string Text
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Text"), @"");
			}
			set
			{
				SetValue("Text", value);
			}
		}


		/// <summary>
		/// Image.
		/// </summary>
		[DatabaseField]
		public Guid TeaserImage
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("TeaserImage"), Guid.Empty);
			}
			set
			{
				SetValue("TeaserImage", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Article fields.
		/// </summary>
		[RegisterProperty]
		public ArticleFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Article fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ArticleFields : AbstractHierarchicalObject<ArticleFields>
		{
			/// <summary>
			/// The content item of type Article that is a target of the extended API.
			/// </summary>
			private readonly Article mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ArticleFields" /> class with the specified content item of type Article.
			/// </summary>
			/// <param name="instance">The content item of type Article that is a target of the extended API.</param>
			public ArticleFields(Article instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ArticleID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ArticleID;
				}
				set
				{
					mInstance.ArticleID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Teaser image.
			/// </summary>
			public DocumentAttachment Image
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("Image");
				}
			}


			/// <summary>
			/// Summary.
			/// </summary>
			public string Summary
			{
				get
				{
					return mInstance.Summary;
				}
				set
				{
					mInstance.Summary = value;
				}
			}


			/// <summary>
			/// Text.
			/// </summary>
			public string Text
			{
				get
				{
					return mInstance.Text;
				}
				set
				{
					mInstance.Text = value;
				}
			}


			/// <summary>
			/// Image.
			/// </summary>
			public DocumentAttachment TeaserImage
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("TeaserImage");
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Article" /> class.
		/// </summary>
		public Article() : base(CLASS_NAME)
		{
			mFields = new ArticleFields(this);
		}

		#endregion
	}
}