//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.Training;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(DoctorSection.CLASS_NAME, typeof(DoctorSection))]

namespace CMS.DocumentEngine.Types.Training
{
	/// <summary>
	/// Represents a content item of type DoctorSection.
	/// </summary>
	public partial class DoctorSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Training.DoctorSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with DoctorSection fields.
		/// </summary>
		private readonly DoctorSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// DoctorSectionID.
		/// </summary>
		[DatabaseIDField]
		public int DoctorSectionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("DoctorSectionID"), 0);
			}
			set
			{
				SetValue("DoctorSectionID", value);
			}
		}


		/// <summary>
		/// Section name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with DoctorSection fields.
		/// </summary>
		[RegisterProperty]
		public DoctorSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with DoctorSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class DoctorSectionFields : AbstractHierarchicalObject<DoctorSectionFields>
		{
			/// <summary>
			/// The content item of type DoctorSection that is a target of the extended API.
			/// </summary>
			private readonly DoctorSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="DoctorSectionFields" /> class with the specified content item of type DoctorSection.
			/// </summary>
			/// <param name="instance">The content item of type DoctorSection that is a target of the extended API.</param>
			public DoctorSectionFields(DoctorSection instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// DoctorSectionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.DoctorSectionID;
				}
				set
				{
					mInstance.DoctorSectionID = value;
				}
			}


			/// <summary>
			/// Section name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="DoctorSection" /> class.
		/// </summary>
		public DoctorSection() : base(CLASS_NAME)
		{
			mFields = new DoctorSectionFields(this);
		}

		#endregion
	}
}