//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.CMS;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(File.CLASS_NAME, typeof(File))]

namespace CMS.DocumentEngine.Types.CMS
{
	/// <summary>
	/// Represents a content item of type File.
	/// </summary>
	public partial class File : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "CMS.File";


		/// <summary>
		/// The instance of the class that provides extended API for working with File fields.
		/// </summary>
		private readonly FileFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FileID.
		/// </summary>
		[DatabaseIDField]
		public int FileID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("FileID"), 0);
			}
			set
			{
				SetValue("FileID", value);
			}
		}


		/// <summary>
		/// File name.
		/// </summary>
		[DatabaseField]
		public string FileName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FileName"), @"");
			}
			set
			{
				SetValue("FileName", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string FileDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FileDescription"), @"");
			}
			set
			{
				SetValue("FileDescription", value);
			}
		}


		/// <summary>
		/// File.
		/// </summary>
		[DatabaseField]
		public Guid FileAttachment
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("FileAttachment"), Guid.Empty);
			}
			set
			{
				SetValue("FileAttachment", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with File fields.
		/// </summary>
		[RegisterProperty]
		public FileFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with File fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class FileFields : AbstractHierarchicalObject<FileFields>
		{
			/// <summary>
			/// The content item of type File that is a target of the extended API.
			/// </summary>
			private readonly File mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="FileFields" /> class with the specified content item of type File.
			/// </summary>
			/// <param name="instance">The content item of type File that is a target of the extended API.</param>
			public FileFields(File instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FileID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.FileID;
				}
				set
				{
					mInstance.FileID = value;
				}
			}


			/// <summary>
			/// File name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.FileName;
				}
				set
				{
					mInstance.FileName = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string Description
			{
				get
				{
					return mInstance.FileDescription;
				}
				set
				{
					mInstance.FileDescription = value;
				}
			}


			/// <summary>
			/// File.
			/// </summary>
			public DocumentAttachment Attachment
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("FileAttachment");
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="File" /> class.
		/// </summary>
		public File() : base(CLASS_NAME)
		{
			mFields = new FileFields(this);
		}

		#endregion
	}
}