//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class CMSModules_AdminControls_Controls_Class_FormBuilder_FormBuilder {
    
    /// <summary>
    /// pnlFormBuilder control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlFormBuilder;
    
    /// <summary>
    /// pnlFormComponents control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSModules_AdminControls_Controls_Class_FormBuilder_FormComponents pnlFormComponents;
    
    /// <summary>
    /// pnlUpdateForm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.Base.Web.UI.CMSUpdatePanel pnlUpdateForm;
    
    /// <summary>
    /// plcMessagesHolder control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.Base.Web.UI.MessagesPlaceHolder plcMessagesHolder;
    
    /// <summary>
    /// hdnFormBuilderUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button hdnFormBuilderUpdate;
    
    /// <summary>
    /// lblEmptyFormPlaceholder control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.Base.Web.UI.LocalizedLabel lblEmptyFormPlaceholder;
    
    /// <summary>
    /// formElem control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.FormEngine.Web.UI.BasicForm formElem;
    
    /// <summary>
    /// pnlSettings control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSModules_AdminControls_Controls_Class_FormBuilder_Settings pnlSettings;
}
